import { Atom, Briefcase, Clapperboard, Coffee, Cpu, GraduationCap, Heart, Landmark, Music, Plane, Stethoscope, Sword, Trophy, Utensils } from "lucide-react";

export const TOPICS = [
    {
        id: "business",
        title: "商务精英",
        description: "谈判、邮件、面试",
        icon: Briefcase,
        color: "bg-blue-50 text-blue-600 border-blue-200",
        gradient: "from-blue-500 to-indigo-600",
        minElo: 0,
    },
    {
        id: "travel",
        title: "环球旅行",
        description: "机场、酒店、紧急情况",
        icon: Plane,
        color: "bg-sky-50 text-sky-600 border-sky-200",
        gradient: "from-sky-400 to-cyan-500",
        minElo: 0,
    },
    {
        id: "academic",
        title: "学术先锋",
        description: "雅思口语、辩论、逻辑",
        icon: GraduationCap,
        color: "bg-indigo-50 text-indigo-600 border-indigo-200",
        gradient: "from-indigo-500 to-purple-600",
        minElo: 0,
    },
    {
        id: "daily",
        title: "日常闲聊",
        description: "搭讪、破冰、闲谈",
        icon: Coffee,
        color: "bg-amber-50 text-amber-600 border-amber-200",
        gradient: "from-amber-400 to-orange-500",
        minElo: 0,
    },
    {
        id: "tech",
        title: "科技前沿",
        description: "AI、创业、编程",
        icon: Cpu,
        color: "bg-violet-50 text-violet-600 border-violet-200",
        gradient: "from-violet-500 to-fuchsia-600",
        minElo: 0,
    },
    {
        id: "romance",
        title: "浪漫火花",
        description: "约会、情感、表白",
        icon: Heart,
        color: "bg-pink-50 text-pink-600 border-pink-200",
        gradient: "from-pink-500 to-rose-500",
        minElo: 0,
    },
    {
        id: "food",
        title: "美食天地",
        description: "餐厅点餐、食谱、美食评论",
        icon: Utensils,
        color: "bg-orange-50 text-orange-600 border-orange-200",
        gradient: "from-orange-500 to-amber-600",
        minElo: 0,
    },
    {
        id: "medical",
        title: "急诊室",
        description: "症状描述、事故、急救",
        icon: Stethoscope,
        color: "bg-red-50 text-red-600 border-red-200",
        gradient: "from-red-500 to-rose-700",
        minElo: 0,
    },
    {
        id: "debate",
        title: "深度辩论",
        description: "哲学、伦理、复杂议题",
        icon: Sword,
        color: "bg-rose-50 text-rose-600 border-rose-200",
        gradient: "from-rose-500 to-red-600",
        minElo: 0,
    },
    {
        id: "movie",
        title: "影视世界",
        description: "电影、剧集、明星八卦",
        icon: Clapperboard,
        color: "bg-purple-50 text-purple-600 border-purple-200",
        gradient: "from-purple-500 to-violet-600",
        minElo: 0,
    },
    {
        id: "music",
        title: "音乐殿堂",
        description: "演唱会、乐器、音乐流派",
        icon: Music,
        color: "bg-teal-50 text-teal-600 border-teal-200",
        gradient: "from-teal-500 to-emerald-600",
        minElo: 0,
    },
    {
        id: "sports",
        title: "体育竞技",
        description: "足球、篮球、奥运会",
        icon: Trophy,
        color: "bg-lime-50 text-lime-600 border-lime-200",
        gradient: "from-lime-500 to-green-600",
        minElo: 0,
    },
    {
        id: "science",
        title: "科学探索",
        description: "太空、物理、生物",
        icon: Atom,
        color: "bg-cyan-50 text-cyan-600 border-cyan-200",
        gradient: "from-cyan-500 to-blue-600",
        minElo: 0,
    },
    {
        id: "history",
        title: "历史长河",
        description: "古代文明、战争、名人",
        icon: Landmark,
        color: "bg-stone-100 text-stone-600 border-stone-200",
        gradient: "from-stone-500 to-stone-700",
        minElo: 0,
    },
] as const;
