import { NextRequest, NextResponse } from "next/server";
import { deepseek } from "@/lib/deepseek";

export async function POST(req: NextRequest) {
    try {
        const { user_translation, reference_english, original_chinese, current_elo, mode = "translation" } = await req.json();

        // Base Elo (Default to 1200 if undefined)
        const userElo = current_elo || 1200;

        let prompt = "";

        if (mode === "listening") {
            // Listening Mode Prompt (Phonetic Alignment + Smart Elo)
            prompt = `
            Act as an expert English Listening Coach AND a Ranking Judge.
            
            Context:
            - User Elo: ${userElo}
            - Task: Transcribe what they heard.
            - Reference: "${reference_english}"
            - User Input: "${user_translation}"

            Analysis Rules:
            1. **Phonetic Drift / ASR Error Awareness**: This text is generated by Speech-to-Text. If a word sounds similar but is spelled wrong (e.g. "Source in motion" vs "Show emotions"), treat it as a **Minor Error (-1 to -2)**, NOT a total failure.
            2. **Homophones**: Neutral for exact homophones.
            3. **Gibberish**: If the sentence makes NO sense, it's a FAIL, even if it sounds slightly similar.
            
            Elo Judgment Rules (Balanced):
            - **Solid Win (+20 to +30)**: Correct meaning, clear pronunciation. No significant errors.
            - **Marginal Win (+5 to +10)**: Meaning is clear, but contains ASR errors or minor grammar slips.
            - **Stagnant (0)**: Hard to understand or significant drift.
            - **Loss (-5 to -15)**: Completely wrong meaning or silence.
            
            CRITICAL SCORING RULE:
            - **PHONETIC REDEMPTION**: If a phrase is clearly an ASR error (sounds right, spelled wrong), give **Partial Credit**, do NOT give full marks unless it's perfect. Do NOT fail them either. Balance it.

            Output JSON:
            {
                "score": 0-10, 
                "elo_adjustment": (Int),
                "judge_reasoning": "Brief ranking feedback (e.g. 'Solid mastery of linking sounds, +12')",
                "segments": [ ... (Standard Alignment) ... ],
                "feedback": { ... }
            }
            `;
        } else {
            // Translation Mode Prompt (Smart Elo)
            prompt = `
            Act as an IELTS Examiner AND a Ranking Judge.
            
            Context:
            - User Elo: ${userElo}
            - Task: Translate Chinese to English.
            - Source: "${original_chinese}"
            - Golden: "${reference_english}"
            - User: "${user_translation}"

            Elo Judgment Rules:
            - **Breakthrough (+25 to +35)**: User used vocabulary/grammar ABOVE their current Elo ${userElo}.
            - **Standard (+10 to +15)**: Correct, but within expected difficulty.
            - **Hesitant (+2 to +5)**: Grammatically correct but awkward or "Chinglish".
            - **Fail (-5 to -15)**: Grammatical collapse or wrong meaning.

            Output JSON:
            {
                "score": 0-10,
                "elo_adjustment": (Int),
                "judge_reasoning": "Brief ranking feedback",
                "feedback": ["Point 1", "Point 2"],
                "improved_version": "..."
            }
            `;
        }

        const completion = await deepseek.chat.completions.create({
            messages: [
                { role: "system", content: "You are a helpful AI tutor. Output JSON only." },
                { role: "user", content: prompt }
            ],
            model: "deepseek-chat",
            response_format: { type: "json_object" },
            temperature: 0.7,
        });

        const content = completion.choices[0].message.content;
        if (!content) throw new Error("No content generated");

        const data = JSON.parse(content);
        return NextResponse.json(data);

    } catch (error) {
        console.error("Score Translation Error:", error);
        return NextResponse.json(
            { error: "Failed to score translation" },
            { status: 500 }
        );
    }
}
